### ISSUE TITLE
Change the go.mod module path

### ISSUE THREAD

**Issue by narendranathreddythota** [kotalco/kotal#1]
➜  Narendranath git:(master) ✗ go get -u github.com/kotalco/kotal                                                 
go: downloading github.com/kotalco/kotal v0.0.0-20200813223727-235173dd6fff
go: github.com/kotalco/kotal upgrade => v0.0.0-20200813223727-235173dd6fff
go get: github.com/kotalco/kotal@v0.0.0-20200813223727-235173dd6fff: parsing go.mod:
        module declares its path as: github.com/mfarghaly/kotal
                but was required as: github.com/kotalco/kotal

go.mod path should always match with the GitHub.com

From `module github.com/mfarghaly/kotal` -> `module github.com/kotalco/kotal` and update the Project

**Comment by mFarghaly** [comment]
Thank you @narendranathreddythota 
go.mod has been updated
