### ISSUE TITLE
Support for Nethermind or OpenEthereum

### ISSUE THREAD

**Issue by igorbarinov** [kotalco/kotal#2]
Hi,

great tool. Found it via Gitcoin grants. 
Do you have any plans to support Nethermind or OpenEthereum clients.
Will be great to put in for test for xDai RPCs.

Thank you

**Comment by mFarghaly** [comment]
Hi @igorbarinov 
Yes, we're supporting OpenEthereum private -PoW & PoA- and public networks.
Check Ethereum 1 docs https://docs.kotal.co/ethereum/intro
Ethereum 1 node reference https://docs.kotal.co/ethereum/reference/node#client

Nethermind support is work in progress, it has been reprioritized due for supporting Ehereum 2.
Now Ethereum 2 is alpha, we will release Nethermind soon.
